name = "fino"
main = "worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "CONTENT"
id = "bb5f2662b2d645d98f5cecbe8e41c4d7"

# Admin password:
# If ADMIN_PASSWORD is not added in Cloudflare, the fallback password is:
# FinovantaAdmin2026!
#
# Better: add a secret/variable in Cloudflare:
# ADMIN_PASSWORD = your_password
